version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: eokjeryeok-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app1234
      POSTGRES_DB: eokjeryeok
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
